### PR TITLE
typo, minor grammar adjustments

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nicolas33** [comment]
Please, read the [DCO](http://www.offlineimap.org/doc/dco.html) and re-submit.
Thanks!

**Comment by nicolas33** [comment]
> Please, read the DCO and re-submit.
> Thanks!

Forget that. This is about the website. I'm not so strict here.

**Comment by nicolas33** [comment]
Applied. Thank you much!

**Comment by ghost** [comment]
no problem; thanks for the tool, quite useful in simplifying my email workflow

**Pull request closed without merging**
